/**
 * SDL 3D Hotspots — 3D Model Viewer
 * Depends on viewer.js (window._sdl3d must be loaded first).
 *
 * Build target: extensions/product-3d-viewer/assets/viewer-3d.js
 * (gitignored, regenerated by `npm run build:tae`).
 */
import type { Sdl3dHotspot, Sdl3dViewerSettings } from "./types";
import { iconHtml, mediaHtml } from "./media";

(function () {
  const S = window._sdl3d;
  if (!S) return;
  const { ce, sa, mkFs, sFb, mkSidebar } = S;

  function applyS(mv: any, R: HTMLElement, s: Sdl3dViewerSettings) {
    const fhl = R.dataset.forceHorizontalLock === "true";
    const fbScope = R.closest(".sdl3d-block") || R;
    const fb = fbScope.querySelector<HTMLButtonElement>("[data-sdl3d-fullscreen]");

    sa(mv, "camera-controls", s?.cameraControls !== false);
    sa(mv, "auto-rotate", s?.autoRotate === true);
    if (s?.autoRotate === true) {
      const spd = typeof s.autoRotateSpeed === "number" ? s.autoRotateSpeed : 30;
      const sign = s.autoRotateDirection === "reverse" ? "-" : "";
      mv.setAttribute("rotation-per-second", sign + spd + "deg");
    } else {
      mv.removeAttribute("rotation-per-second");
    }
    if (s?.cameraOrbit) mv.setAttribute("camera-orbit", s.cameraOrbit);
    if (s?.cameraTarget) mv.setAttribute("camera-target", s.cameraTarget);
    if (s?.fieldOfView) mv.setAttribute("field-of-view", s.fieldOfView);
    if (typeof s?.exposure === "number") mv.setAttribute("exposure", String(s.exposure));
    if (s?.interactionPrompt) mv.setAttribute("interaction-prompt", s.interactionPrompt);

    const hz = fhl || s?.horizontalLock || s?.rotationMode === "horizontal_only";
    if (hz) {
      const pa = s?.lockedPolarAngle
        || (typeof s?.cameraOrbit === "string" ? s.cameraOrbit.trim().split(/\s+/)[1] : null)
        || "75deg";
      const lo = "auto " + pa + " auto";
      mv.setAttribute("min-camera-orbit", lo);
      mv.setAttribute("max-camera-orbit", lo);
    } else {
      if (s?.minCameraOrbit) mv.setAttribute("min-camera-orbit", s.minCameraOrbit);
      else mv.removeAttribute("min-camera-orbit");
      if (s?.maxCameraOrbit) mv.setAttribute("max-camera-orbit", s.maxCameraOrbit);
      else mv.removeAttribute("max-camera-orbit");
    }

    if (s?.backgroundColor) R.style.setProperty("--sdl3d-background", s.backgroundColor);

    if (fb) {
      if (R.dataset.showFullscreen === "true" || s?.showFullscreen === true) {
        fb.hidden = false;
        fb.addEventListener("click", function () { R.requestFullscreen && R.requestFullscreen(); });
      } else {
        fb.hidden = true;
      }
    }

    const rb = fbScope.querySelector<HTMLButtonElement>("[data-sdl3d-reset]");
    if (rb && !rb.dataset.sdl3dResetBound) {
      rb.dataset.sdl3dResetBound = "1";
      rb.addEventListener("click", function () {
        if (s?.cameraOrbit) mv.setAttribute("camera-orbit", s.cameraOrbit);
        if (s?.cameraTarget) mv.setAttribute("camera-target", s.cameraTarget);
        mv.querySelectorAll(".sdl3d-hotspot.is-active").forEach(function (n: Element) { n.classList.remove("is-active"); });
        if ((R as any)._sidebar && (R as any)._sidebar._clearSelection) (R as any)._sidebar._clearSelection();
      });
    }
  }

  function mkH(h: Sdl3dHotspot, i: number): HTMLButtonElement {
    const l = h.title || "Hotspot " + (i + 1);
    const b = ce("button", "sdl3d-hotspot sdl3d-hotspot--" + (h.style || "card")) as HTMLButtonElement;
    b.type = "button";
    b.slot = "hotspot-" + (h.id || i + 1);
    b.dataset.position = h.position || "0m 0m 0m";
    if (h.normal) b.dataset.normal = h.normal;
    if (h.color) b.style.setProperty("--sdl3d-hotspot-color", h.color);
    b.dataset.ft = h.focusTarget || h.position || "0m 0m 0m";
    if (h.focusOrbit) b.dataset.fo = h.focusOrbit;
    if (h.animation && h.animation !== "none") b.dataset.sdl3dAnim = h.animation;
    b.ariaLabel = l;
    b.dataset.hsIndex = String(i);

    // PR #5 follow-up — popup card stripped. All hotspot info renders
    // in the right sidebar; the button carries only the dot.
    const d = ce("span", "sdl3d-hotspot__dot");
    const iconMarkup = iconHtml(h.icon);
    if (iconMarkup) {
      d.classList.add("sdl3d-hotspot__dot--icon");
      d.innerHTML = iconMarkup;
    } else {
      d.textContent = String(i + 1);
    }
    b.appendChild(d);

    b.addEventListener("click", function () {
      const mv = b.closest("model-viewer");
      if (!mv) return;
      if (b.dataset.ft) mv.setAttribute("camera-target", b.dataset.ft);
      if (b.dataset.fo) mv.setAttribute("camera-orbit", b.dataset.fo);
      mv.querySelectorAll(".sdl3d-hotspot.is-active").forEach(function (n: Element) { n.classList.remove("is-active"); });
      b.classList.add("is-active");
      const root = (mv.closest(".sdl3d-viewer") || mv.closest("[data-sdl3d-app-root]")) as any;
      if (root && root._sidebar) root._sidebar._selectIndex(parseInt(b.dataset.hsIndex!, 10));
    });
    return b;
  }

  function aH(mv: any, list: Sdl3dHotspot[]) {
    mv.querySelectorAll(".sdl3d-hotspot").forEach(function (n: Element) { n.remove(); });
    if (!Array.isArray(list) || !list.length) return;
    list
      .filter(function (h) { return h && h.visible !== false && h.position; })
      .sort(function (a, b) { return (a.sortOrder || 0) - (b.sortOrder || 0); })
      .forEach(function (h, i) { mv.appendChild(mkH(h, i)); });
  }

  function init3d(R: HTMLElement) {
    const mv = R.querySelector<HTMLElement>("[data-sdl3d-model]");
    if (!mv) return;
    mv.addEventListener("error", function () { sFb(R); });
    const vs = S.jd<Sdl3dViewerSettings>(R, "[data-sdl3d-viewer-settings]", {});
    const hs = S.jd<Sdl3dHotspot[]>(R, "[data-sdl3d-hotspots]", []);
    applyS(mv as any, R, vs);

    const filtered = (hs || [])
      .filter(function (h) { return h && h.visible !== false && h.position; })
      .sort(function (a, b) { return (a.sortOrder || 0) - (b.sortOrder || 0); });

    aH(mv as any, filtered);

    const sb = mkSidebar(filtered, function (h, i) {
      if (h.focusTarget || h.position) (mv as any).setAttribute("camera-target", h.focusTarget || h.position);
      if (h.focusOrbit) (mv as any).setAttribute("camera-orbit", h.focusOrbit);
      mv.querySelectorAll(".sdl3d-hotspot.is-active").forEach(function (n: Element) { n.classList.remove("is-active"); });
      const dots = mv.querySelectorAll(".sdl3d-hotspot");
      if (dots[i]) dots[i].classList.add("is-active");
    }, { renderMedia: function (h) { return mediaHtml(h.mediaImageUrl, h.mediaVideoUrl, "3d"); } });
    const sbHost = (R.closest(".sdl3d-block__body") || R.parentNode) as HTMLElement;
    const old = sbHost.querySelector(":scope > .sdl3d-sidebar");
    if (old) old.remove();
    sbHost.appendChild(sb);
    (R as any)._sidebar = sb;

    R.dataset.sdl3dInitialized = "true";
  }

  function aIM(R: HTMLElement, c: any) {
    const mv = ce("model-viewer", "sdl3d-viewer__model") as any;
    mv.dataset.sdl3dModel = "1";
    mv.setAttribute("src", c.modelSourceUrl || "");
    mv.setAttribute("camera-controls", "");
    mv.setAttribute("auto-rotate", "");
    mv.setAttribute("reveal", "auto");
    mv.loading = "eager";
    if (c.posterUrl) mv.setAttribute("poster", c.posterUrl);
    if (c.fallbackImageUrl) R.dataset.fallbackImage = c.fallbackImageUrl;
    mv.addEventListener("error", function () { sFb(R); });
    const blk = R.closest(".sdl3d-block");
    if (!blk || !blk.querySelector("[data-sdl3d-fullscreen]")) {
      mv.appendChild(mkFs());
    }
    R.className = "sdl3d-viewer";
    R.appendChild(mv);
    S.loadMV().then(function () {
      applyS(mv, R, c.viewerSettings || {});
      const filtered = (c.hotspots || [])
        .filter(function (h: Sdl3dHotspot) { return h && h.visible !== false && h.position; })
        .sort(function (a: Sdl3dHotspot, b: Sdl3dHotspot) { return (a.sortOrder || 0) - (b.sortOrder || 0); });
      aH(mv, filtered);

      const sb = mkSidebar(filtered, function (h, i) {
        if (h.focusTarget || h.position) mv.setAttribute("camera-target", h.focusTarget || h.position);
        if (h.focusOrbit) mv.setAttribute("camera-orbit", h.focusOrbit);
        mv.querySelectorAll(".sdl3d-hotspot.is-active").forEach(function (n: Element) { n.classList.remove("is-active"); });
        const dots = mv.querySelectorAll(".sdl3d-hotspot");
        if (dots[i]) dots[i].classList.add("is-active");
      }, { renderMedia: function (h) { return mediaHtml(h.mediaImageUrl, h.mediaVideoUrl, "3d"); } });
      const sbHost = (R.closest(".sdl3d-block__body") || R.parentNode) as HTMLElement;
      const old = sbHost.querySelector(":scope > .sdl3d-sidebar");
      if (old) old.remove();
      sbHost.appendChild(sb);
      (R as any)._sidebar = sb;
    });
  }

  S.applyS = applyS;
  S.init3d = init3d;
  S.aIM = aIM;
})();
