/* SDL 3D Hotspots — 360° Image Sequence Viewer
 *
 * Build target: extensions/product-3d-viewer/assets/viewer-360.js
 * (gitignored, regenerated by `npm run build:tae`).
 *
 * Interpolation note — `interp()` below is still parallel to
 * app/lib/sdl3d-shared.ts's `interpolateHotspotPosition`. Promoting it
 * to @spectrum-design-lab/shared is the next follow-up after this PR
 * (it's the largest remaining duplicate but has more interaction with
 * frame state than the small constants moved in this round).
 */
import type {
  Sdl3dHotspot360,
  Sdl3dHotspot360Keyframe,
  Sdl3dImageSequenceFrame,
  Sdl3dViewerSettings,
} from "./types";
import { iconHtml, mediaHtml } from "./media";

(function () {
  const S = window._sdl3d;
  if (!S) return;
  const { ce, jd, mkFs } = S;

  function cr(p0: number, p1: number, p2: number, p3: number, t: number): number {
    return 0.5 * (2 * p1 + (-p0 + p2) * t + (2 * p0 - 5 * p1 + 4 * p2 - p3) * t * t + (-p0 + 3 * p1 - 3 * p2 + p3) * t * t * t);
  }

  function interp(
    kf: Sdl3dHotspot360Keyframe[] | undefined,
    frame: number,
    wrap: boolean,
    totalFrames: number,
  ): { x: number; y: number } | null {
    if (!kf || !kf.length) return null;
    const sorted = kf.slice().sort(function (a, b) { return a.frame - b.frame; });
    const last = sorted.length - 1;
    const first = sorted[0];
    const lastKf = sorted[last];
    const wrapMode = wrap === true && (totalFrames || 0) > 0;

    if (wrapMode && sorted.length >= 2 && (frame > lastKf.frame || frame < first.frame)) {
      const span = totalFrames - lastKf.frame + first.frame;
      const offset = frame > lastKf.frame
        ? frame - lastKf.frame
        : totalFrames - lastKf.frame + frame;
      const t = span > 0 ? offset / span : 0;
      return {
        x: lastKf.x + (first.x - lastKf.x) * t,
        y: lastKf.y + (first.y - lastKf.y) * t,
      };
    }

    if (frame <= first.frame) return first;
    if (frame >= lastKf.frame) return lastKf;
    for (let j = 0; j < last; j++) {
      const a = sorted[j], b = sorted[j + 1];
      if (frame >= a.frame && frame <= b.frame) {
        const t2 = (frame - a.frame) / (b.frame - a.frame);
        if (sorted.length < 3) return { x: a.x + (b.x - a.x) * t2, y: a.y + (b.y - a.y) * t2 };
        const p0 = sorted[Math.max(j - 1, 0)], p3 = sorted[Math.min(j + 2, last)];
        return { x: cr(p0.x, a.x, b.x, p3.x, t2), y: cr(p0.y, a.y, b.y, p3.y, t2) };
      }
    }
    return null;
  }

  // Responsive sizing: Shopify CDN supports ?width= as a query-string transform,
  // so we right-size frames to the viewport. Other origins (DigitalOcean Spaces,
  // localhost dev server, etc.) don't support this and download full-resolution.
  function cdnSize(url: string, w: number): string {
    if (!url || url.indexOf("cdn.shopify.com") === -1) return url;
    const cw = w <= 600 ? 800 : w <= 1200 ? 1200 : 1800;
    return url + (url.indexOf("?") === -1 ? "?" : "&") + "width=" + cw;
  }

  function preloadFrames(urls: string[], onProgress?: (idx: number) => void): HTMLImageElement[] {
    const imgs = new Array(urls.length) as HTMLImageElement[];
    const priority: number[] = [], rest: number[] = [];
    const step = Math.max(1, Math.ceil(urls.length / 8));
    for (let i = 0; i < urls.length; i++) {
      if (i % step === 0) priority.push(i); else rest.push(i);
    }
    const order = priority.concat(rest);
    let batch = 4, qi = 0;
    function loadNext() {
      while (qi < order.length && batch > 0) {
        batch--;
        (function (idx) {
          const im = new Image();
          im.onload = function () {
            imgs[idx] = im; batch++;
            if (onProgress) onProgress(idx);
            loadNext();
          };
          im.onerror = function () { batch++; loadNext(); };
          im.src = urls[idx];
        })(order[qi]);
        qi++;
      }
    }
    loadNext();
    return imgs;
  }

  function mk3H(h: Sdl3dHotspot360, i: number): HTMLButtonElement {
    const label = h.title || "Hotspot " + (i + 1);
    const b = ce("button", "sdl3d-360-hotspot sdl3d-360-hotspot--" + (h.style || "card")) as HTMLButtonElement;
    b.type = "button";
    b.ariaLabel = label;
    b.dataset.hsIndex = String(i);
    if (h.color) b.style.setProperty("--sdl3d-hotspot-color", h.color);
    if (h.animation && h.animation !== "none") b.dataset.sdl3dAnim = h.animation;

    const dot = ce("span", "sdl3d-360-hotspot__dot");
    const iconMarkup = iconHtml(h.icon);
    if (iconMarkup) {
      dot.classList.add("sdl3d-360-hotspot__dot--icon");
      dot.innerHTML = iconMarkup;
    } else {
      dot.textContent = String(i + 1);
    }
    b.appendChild(dot);
    b.addEventListener("click", function (e) {
      e.stopPropagation();
      const p = b.closest("[data-sdl3d-360-root],[data-sdl3d-app-root]") as any;
      if (p) {
        p.querySelectorAll(".sdl3d-360-hotspot.is-active").forEach(function (n: Element) { n.classList.remove("is-active"); });
        if (p._sidebar) p._sidebar._selectIndex(parseInt(b.dataset.hsIndex!, 10));
      }
      b.classList.add("is-active");
    });
    return b;
  }

  function s360(
    R: HTMLElement,
    vp: HTMLElement,
    img: HTMLImageElement,
    seq: Sdl3dImageSequenceFrame[],
    hotspots: Sdl3dHotspot360[],
    vs: Sdl3dViewerSettings,
  ) {
    if (!seq.length) return;
    const fc = seq.length;
    let cf = 0, dragging = false, startX = 0, startFrame = 0;
    let autoRotateTimer: any = null;
    const hotspotEls: { h: Sdl3dHotspot360; el: HTMLElement }[] = [];
    const vpW = vp.clientWidth || 800;

    if (vs.backgroundColor) R.style.setProperty("--sdl3d-background", vs.backgroundColor);
    const sizedUrls = seq.map(function (f) {
      return f.imageUrl ? cdnSize(f.imageUrl, vpW) : "";
    });
    const frameImgs = preloadFrames(sizedUrls.filter(Boolean).length ? sizedUrls : [], function (idx) {
      if (idx === 0 && frameImgs[0]) drawFrame(0);
    });

    const canvas = ce("canvas", "sdl3d-360-canvas") as HTMLCanvasElement;
    canvas.style.cssText = "position:absolute;top:0;left:0;width:100%;height:100%;object-fit:contain";
    const ctx = canvas.getContext("2d")!;
    let canvasReady = false;

    function sizeCanvas() {
      const w = vp.clientWidth || 800;
      const h = vp.clientHeight || 600;
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      canvas.width = w * dpr;
      canvas.height = h * dpr;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    }

    function drawFrame(f: number): boolean {
      const im = frameImgs[f];
      if (!im) return false;
      if (!canvasReady) {
        sizeCanvas();
        vp.appendChild(canvas);
        img.style.visibility = "hidden";
        canvasReady = true;
      }
      const cw = vp.clientWidth || 800;
      const ch = vp.clientHeight || 600;
      const scale = Math.min(cw / im.naturalWidth, ch / im.naturalHeight);
      const dw = im.naturalWidth * scale;
      const dh = im.naturalHeight * scale;
      ctx.clearRect(0, 0, cw, ch);
      ctx.drawImage(im, (cw - dw) / 2, (ch - dh) / 2, dw, dh);
      return true;
    }

    function setFrame(f: number) {
      cf = ((f % fc) + fc) % fc;
      if (!drawFrame(cf)) {
        const d = seq[cf];
        if (d && d.imageUrl) img.src = cdnSize(d.imageUrl, vpW);
      }
      updateHotspots();
    }

    function updateHotspots() {
      hotspotEls.forEach(function (item) {
        const wraps = (item.h.visibleFrameStart || 0) > (item.h.visibleFrameEnd || 0);
        const p = interp(item.h.keyframes, cf, wraps, fc);
        const start = item.h.visibleFrameStart || 0;
        const end = item.h.visibleFrameEnd || 0;
        const visible = item.h.visible !== false && (
          wraps
            ? (cf >= start || cf <= end)
            : (cf >= start && cf <= end)
        );
        if (visible && p) {
          item.el.style.display = "";
          item.el.style.left = p.x + "%";
          item.el.style.top = p.y + "%";
        } else {
          item.el.style.display = "none";
        }
      });
    }

    hotspots
      .filter(function (h) { return h && h.keyframes && h.keyframes.length; })
      .sort(function (a, b) { return (a.sortOrder || 0) - (b.sortOrder || 0); })
      .forEach(function (h, i) {
        const el = mk3H(h, i);
        el.style.cssText = "position:absolute;transform:translate(-50%,-50%)";
        vp.appendChild(el);
        hotspotEls.push({ h, el });
      });

    const filteredForSidebar = hotspots
      .filter(function (h) { return h && h.keyframes && h.keyframes.length; })
      .sort(function (a, b) { return (a.sortOrder || 0) - (b.sortOrder || 0); });

    const mkSidebar = S.mkSidebar;
    const sbHost = (R.closest(".sdl3d-block__body") || R.parentNode) as HTMLElement;
    if (mkSidebar) {
      const sb = mkSidebar(filteredForSidebar, function (h, i) {
        // Wraparound-aware midpoint (Slice 7 PR #6).
        const start = h.visibleFrameStart || 0;
        const end = h.visibleFrameEnd || 0;
        let mid: number;
        if (start > end && fc > 0) {
          const span = fc - start + end;
          mid = (start + Math.floor(span / 2)) % fc;
        } else {
          mid = Math.round((start + end) / 2);
        }
        setFrame(mid);
        R.querySelectorAll(".sdl3d-360-hotspot.is-active").forEach(function (n: Element) { n.classList.remove("is-active"); });
        if (hotspotEls[i]) hotspotEls[i].el.classList.add("is-active");
      }, { renderMedia: function (h) { return mediaHtml((h as Sdl3dHotspot360).mediaImageUrl, (h as Sdl3dHotspot360).mediaVideoUrl, "360"); } });
      const old = sbHost.querySelector(":scope > .sdl3d-sidebar");
      if (old) old.remove();
      sbHost.appendChild(sb);
      (R as any)._sidebar = sb;
    }

    let pendingFrame: number | null = null;
    vp.addEventListener("pointerdown", function (e) {
      if ((e.target as Element).closest(".sdl3d-360-hotspot")) return;
      dragging = true;
      startX = e.clientX;
      startFrame = cf;
      vp.setPointerCapture(e.pointerId);
      if (autoRotateTimer) { clearInterval(autoRotateTimer); autoRotateTimer = null; }
    });
    vp.addEventListener("pointermove", function (e) {
      if (!dragging) return;
      // Drag direction: dragging RIGHT spins the object so the merchant
      // sees the LEFT side of the product come around — i.e. the camera
      // moves left relative to the object. Subtract the pixel delta so
      // the frame index goes BACKWARD as the cursor moves right. (Felt
      // backwards before; merchant feedback 2026-05-27.)
      const target = startFrame - Math.round((e.clientX - startX) / (vp.clientWidth || 600) * fc);
      if (pendingFrame !== null) { pendingFrame = target; return; }
      pendingFrame = target;
      requestAnimationFrame(function () {
        setFrame(pendingFrame!);
        pendingFrame = null;
      });
    });
    vp.addEventListener("pointerup", function () { dragging = false; });
    vp.addEventListener("lostpointercapture", function () { dragging = false; });

    window.addEventListener("resize", function () {
      if (canvasReady) { sizeCanvas(); drawFrame(cf); }
    });

    if (vs.autoRotate === true) {
      const spd = typeof vs.autoRotateSpeed === "number" ? vs.autoRotateSpeed : 30;
      const step = vs.autoRotateDirection === "reverse" ? -1 : 1;
      const ms = Math.max(20, Math.round((360 / spd) * (1000 / Math.max(1, fc))));
      autoRotateTimer = setInterval(function () { setFrame(cf + step); }, ms);
    }

    const fbScope = R.closest(".sdl3d-block") || R;
    const fb = fbScope.querySelector<HTMLButtonElement>("[data-sdl3d-fullscreen]");
    if (fb && R.dataset.showFullscreen === "true") {
      fb.hidden = false;
      fb.addEventListener("click", function () { R.requestFullscreen && R.requestFullscreen(); });
    }

    const rb = fbScope.querySelector<HTMLButtonElement>("[data-sdl3d-reset]");
    if (rb) {
      rb.addEventListener("click", function () {
        setFrame(0);
        R.querySelectorAll(".sdl3d-360-hotspot.is-active").forEach(function (n: Element) { n.classList.remove("is-active"); });
        if ((R as any)._sidebar && (R as any)._sidebar._clearSelection) (R as any)._sidebar._clearSelection();
      });
    }

    setFrame(0);
    R.dataset.sdl3d360Initialized = "true";
  }

  function i360(R: HTMLElement) {
    const vp = R.querySelector<HTMLElement>("[data-sdl3d-360-viewport]");
    const img = R.querySelector<HTMLImageElement>("[data-sdl3d-360-image]");
    if (!vp || !img) return;
    s360(R, vp, img,
      jd<Sdl3dImageSequenceFrame[]>(R, "[data-sdl3d-image-sequence]", []),
      jd<Sdl3dHotspot360[]>(R, "[data-sdl3d-hotspots-360]", []),
      jd<Sdl3dViewerSettings>(R, "[data-sdl3d-viewer-settings]", {}),
    );
  }

  function aI3(R: HTMLElement, c: any) {
    const vp = ce("div", "sdl3d-360-viewport") as HTMLDivElement;
    vp.dataset.sdl3d360Viewport = "1";
    const img = ce("img", "sdl3d-360-image") as HTMLImageElement;
    img.dataset.sdl3d360Image = "1";
    img.src = c.posterUrl || "";
    img.alt = "360° view";
    img.width = 1200;
    img.height = 900;
    img.draggable = false;
    vp.appendChild(img);
    R.className = "sdl3d-360-viewer";
    R.appendChild(vp);
    const blk = R.closest(".sdl3d-block");
    if (!blk || !blk.querySelector("[data-sdl3d-fullscreen]")) {
      R.appendChild(mkFs());
    }
    s360(R, vp, img, c.imageSequence || [], c.hotspots360 || [], c.viewerSettings || {});
  }

  S.i360 = i360;
  S.aI3 = aI3;
})();
