/* SDL 3D Hotspots core bootstrap. 3D code: viewer-3d.js. 360: viewer-360.js.
 *
 * Build target: extensions/product-3d-viewer/assets/viewer.js (gitignored,
 * regenerated by `npm run build:tae`). Stays under the 10KB
 * AppBlockJavaScript cap — no imports from @spectrum-design-lab/shared
 * here (those import in viewer-3d.ts / viewer-360.ts where the lazy-loaded
 * size budget is generous).
 */
import type { SdlGlobal, SidebarElement, Sdl3dHotspot, SidebarOpts } from "./types";

(function () {
  let mvP: Promise<unknown> | null = null;
  const MV_CDN = "https://unpkg.com/@google/model-viewer@4.2.0/dist/model-viewer.min.js";

  function ce(tag: string, cls?: string): HTMLElement {
    const e = document.createElement(tag);
    if (cls) e.className = cls;
    return e;
  }

  function jd<T>(root: Element, selector: string, fallback: T): T {
    const node = root.querySelector(selector);
    if (!node) return fallback;
    try { return JSON.parse(node.textContent || "") as T; }
    catch { return fallback; }
  }

  function sa(el: Element, attr: string, on: boolean) {
    if (on) el.setAttribute(attr, "");
    else el.removeAttribute(attr);
  }

  function loadMV(): Promise<unknown> {
    if (customElements.get("model-viewer")) return Promise.resolve();
    if (mvP) return mvP;
    mvP = new Promise(function (ok, fail) {
      let m = document.querySelector("script[data-sdl3d-mv]") as HTMLScriptElement | null;
      if (!m) {
        const el = document.querySelector("[data-sdl3d-mv-src]");
        const url = (el && el.getAttribute("data-sdl3d-mv-src")) || MV_CDN;
        m = ce("script") as HTMLScriptElement;
        m.type = "module";
        m.src = url;
        m.dataset.sdl3dMv = "1";
        document.head.appendChild(m);
      }
      m.addEventListener("error", fail, { once: true });
      customElements.whenDefined("model-viewer").then(ok);
    });
    return mvP;
  }

  function mkFs(): HTMLButtonElement {
    const b = ce("button", "sdl3d-fullscreen-button") as HTMLButtonElement;
    b.type = "button";
    b.dataset.sdl3dFullscreen = "1";
    b.hidden = true;
    b.textContent = "⛶";
    return b;
  }

  function sFb(R: HTMLElement) {
    const f = R.dataset.fallbackImage;
    if (!f) return;
    R.innerHTML = "";
    const img = ce("img", "sdl3d-fallback-image") as HTMLImageElement;
    img.src = f;
    img.alt = "";
    img.style.cssText = "width:100%;height:100%;object-fit:contain";
    R.appendChild(img);
  }

  function mkSidebar(
    hotspots: Sdl3dHotspot[],
    onSelect?: (h: Sdl3dHotspot, i: number) => void,
    opts?: SidebarOpts,
  ): SidebarElement {
    const renderMedia = opts && opts.renderMedia;
    const sb = ce("div", "sdl3d-sidebar") as SidebarElement;
    let menuOpen = false;
    let selectedIndex = -1;

    const hdr = ce("div", "sdl3d-sidebar__header");
    const hdrTitle = ce("span", "sdl3d-sidebar__header-title");
    hdrTitle.textContent = "Product features";
    hdr.appendChild(hdrTitle);

    const burger = ce("button", "sdl3d-sidebar__burger") as HTMLButtonElement;
    burger.type = "button";
    burger.ariaLabel = "Toggle hotspot list";
    burger.innerHTML = '<svg width="20" height="20" viewBox="0 0 20 20" fill="none"><rect x="2" y="4" width="16" height="2" rx="1" fill="currentColor"/><rect x="2" y="9" width="16" height="2" rx="1" fill="currentColor"/><rect x="2" y="14" width="16" height="2" rx="1" fill="currentColor"/></svg>';
    if (hotspots && hotspots.length) hdr.appendChild(burger);
    sb.appendChild(hdr);

    const content = ce("div", "sdl3d-sidebar__content");

    const prompt = ce("div", "sdl3d-sidebar__prompt");
    const promptIcon = ce("div", "sdl3d-sidebar__prompt-icon");
    promptIcon.innerHTML = '<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>';
    const promptText = ce("div", "sdl3d-sidebar__prompt-text");
    promptText.textContent = "Select a hotspot for feature details";
    prompt.appendChild(promptIcon);
    prompt.appendChild(promptText);
    content.appendChild(prompt);

    const detail = ce("div", "sdl3d-sidebar__detail");
    const dtitle = ce("div", "sdl3d-sidebar__detail-title");
    const dbody = ce("div", "sdl3d-sidebar__detail-body");
    const dmedia = ce("div", "sdl3d-sidebar__detail-media");
    const dcta = ce("a", "sdl3d-sidebar__detail-cta") as HTMLAnchorElement;
    dcta.target = "_blank";
    dcta.rel = "noopener";
    dcta.style.display = "none";
    const dclear = ce("button", "sdl3d-sidebar__clear") as HTMLButtonElement;
    dclear.type = "button";
    dclear.textContent = "Clear selection";
    detail.appendChild(dtitle);
    detail.appendChild(dbody);
    detail.appendChild(dmedia);
    detail.appendChild(dcta);
    detail.appendChild(dclear);
    content.appendChild(detail);

    const list = ce("div", "sdl3d-sidebar__list");

    if (hotspots && hotspots.length) {
      hotspots.forEach(function (h, i) {
        const item = ce("button", "sdl3d-sidebar__item") as HTMLButtonElement;
        item.type = "button";
        const num = ce("span", "sdl3d-sidebar__item-number");
        num.textContent = String(i + 1);
        if (h.color) num.style.setProperty("--sdl3d-hotspot-color", h.color);
        const title = ce("span", "sdl3d-sidebar__item-title");
        title.textContent = h.title || "Hotspot " + (i + 1);
        item.appendChild(num);
        item.appendChild(title);
        list.appendChild(item);
        item.addEventListener("click", function () {
          selectHotspot(h, i);
          if (onSelect) onSelect(h, i);
        });
      });
    }
    content.appendChild(list);
    sb.appendChild(content);

    function showView(view: "prompt" | "detail" | "list") {
      prompt.classList.toggle("is-visible", view === "prompt");
      detail.classList.toggle("is-visible", view === "detail");
      list.classList.toggle("is-visible", view === "list");
      sb.classList.toggle("is-menu-open", view === "list");
    }

    function selectHotspot(h: Sdl3dHotspot, i: number) {
      selectedIndex = i;
      menuOpen = false;
      dtitle.textContent = h.title || "Hotspot " + (i + 1);
      dbody.textContent = h.body || "";
      dmedia.innerHTML = renderMedia ? (renderMedia(h) || "") : "";
      if (h.ctaLabel && h.ctaUrl) {
        dcta.textContent = h.ctaLabel;
        dcta.href = h.ctaUrl;
        dcta.style.display = "";
      } else {
        dcta.style.display = "none";
      }
      list.querySelectorAll(".sdl3d-sidebar__item.is-active")
        .forEach(function (n) { n.classList.remove("is-active"); });
      const items = list.querySelectorAll(".sdl3d-sidebar__item");
      if (items[i]) items[i].classList.add("is-active");
      showView("detail");
    }

    burger.addEventListener("click", function () {
      menuOpen = !menuOpen;
      if (menuOpen) {
        showView("list");
      } else {
        showView(selectedIndex >= 0 ? "detail" : "prompt");
      }
    });

    showView("prompt");

    sb._selectIndex = function (idx: number) {
      if (!hotspots || !hotspots[idx]) return;
      selectHotspot(hotspots[idx], idx);
    };
    sb._clearSelection = function () {
      selectedIndex = -1;
      menuOpen = false;
      list.querySelectorAll(".sdl3d-sidebar__item.is-active")
        .forEach(function (n) { n.classList.remove("is-active"); });
      showView("prompt");
    };

    dclear.addEventListener("click", function () {
      sb._clearSelection();
      const blk = sb.closest(".sdl3d-block");
      if (blk) {
        blk.querySelectorAll(".sdl3d-hotspot.is-active, .sdl3d-360-hotspot.is-active")
          .forEach(function (n) { n.classList.remove("is-active"); });
      }
    });

    return sb;
  }

  const S: SdlGlobal = {
    ce, jd, sa, mkFs, sFb, mkSidebar, loadMV,
  };
  window._sdl3d = S;

  let _3dP: Promise<unknown> | null = null;
  function load3d(): Promise<unknown> {
    if (_3dP) return _3dP;
    if (S.init3d) return Promise.resolve();
    const el = document.querySelector("[data-sdl3d-3d-src]");
    const src = el && el.getAttribute("data-sdl3d-3d-src");
    if (!src) return Promise.resolve();
    _3dP = new Promise(function (ok, fail) {
      const s = ce("script") as HTMLScriptElement;
      s.src = src;
      s.onload = ok as any;
      s.onerror = fail;
      document.head.appendChild(s);
    });
    return _3dP;
  }

  let _360P: Promise<unknown> | null = null;
  function load360(): Promise<unknown> {
    if (_360P) return _360P;
    if (S.i360) return Promise.resolve();
    const el = document.querySelector("[data-sdl3d-360-src]");
    const src = el && el.getAttribute("data-sdl3d-360-src");
    if (!src) return Promise.resolve();
    _360P = new Promise(function (ok, fail) {
      const s = ce("script") as HTMLScriptElement;
      s.src = src;
      s.onload = ok as any;
      s.onerror = fail;
      document.head.appendChild(s);
    });
    return _360P;
  }

  function iApp(R: HTMLElement) {
    if (R.dataset.sdl3dAppInit === "1") return;
    R.dataset.sdl3dAppInit = "1";
    const u = R.dataset.sdl3dProxyUrl;
    if (!u) return;
    fetch(u)
      .then(function (r) { return r.json(); })
      .then(function (c) {
        if (!c || c.error || !c.enabled) {
          R.innerHTML = "<div class=sdl3d-block__message>" + (c && c.error || "N/A") + "</div>";
          return;
        }
        R.innerHTML = "";
        if (c.viewerType === "image_360") {
          load360().then(function () { if (S.aI3) S.aI3(R, c); });
        } else {
          load3d().then(function () { if (S.aIM) S.aIM(R, c); });
        }
      })
      .catch(function () {
        R.innerHTML = "<div class=sdl3d-block__message>Load error</div>";
      });
  }

  function initAll() {
    const r3d = document.querySelectorAll<HTMLElement>("[data-sdl3d-root]");
    if (r3d.length) {
      load3d().then(function () {
        if (!S.init3d) return;
        loadMV()
          .then(function () { r3d.forEach(S.init3d!); })
          .catch(function () { r3d.forEach(sFb); });
      });
    }

    load360().then(function () {
      if (S.i360) {
        document.querySelectorAll<HTMLElement>("[data-sdl3d-360-root]").forEach(function (r) {
          if (r.dataset.sdl3d360Initialized !== "true") S.i360!(r);
        });
      }
    });

    document.querySelectorAll<HTMLElement>("[data-sdl3d-app-root]").forEach(function (r) { iApp(r); });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initAll);
  } else {
    initAll();
  }
  document.addEventListener("shopify:section:load", initAll);
  document.addEventListener("shopify:block:select", initAll);
})();
